### PR TITLE
Kirki upgrade

### PR DESCRIPTION
**Pull request by boonebgorges**
The Kirki library, used by pressforward-turnkey-theme to add Customizer panels, does not appear to be compatible with recent versions of WordPress. This pull request updates the library to its latest version. 

The library upgrade caused one obvious break, where certain panels weren't being properly recognized by Kirki and/or the Customizer (not sure which) because of a naming mismatch: 'block2' and 'Block2' were recognized as equivalent prior to the upgrade, but the upgraded library appears to be case-sensitive.

I'm not familiar enough with the theme to understand whether the upgrade causes other issues, but I'll note that these changes have been in production on the CUNY Academic Commons for several weeks and we haven't received further bug reports.

### CODE REVIEW

**Comment by lmrhody** [comment]
@regan008 I've seen it working on CAC. I think it would be helpful to merge with the base branch.

**Comment by regan008** [comment]
@lmrhody No problem - will merge it this afternoon.

**Comment by regan008** [comment]
And thanks @boonebgorges -- I haven't used this theme in a long time, so I appreciate the fixes as I was unaware the new version of WordPress broke things.

**Comment by lmrhody** [comment]
Thanks, Mandy!!!

~~~~~~~~~~~~~~~~~~~~
Lisa Marie Rhody, Ph.D.
Deputy Director of Digital Initiatives
Director, Digital Humanities Research Institute
Director, Digital Fellowship Programs
Affiliated Faculty, Masters in Digital Humanities, Data Analysis & Visualization,
Liberal Studies, and Interactive Technology and Pedagogy Certificate
The Graduate Center, CUNY
365 Fifth Ave., Room 3300.01
New York, NY 10016
lrhody@gc.cuny.edu<mailto:lrhody@gc.cuny.edu> | @lmrhody | she/her
~~~~~~~~~~~~~~~~~~~~~


On November 17, 2020 at 10:10:52 AM, Amanda Regan (notifications@github.com<mailto:notifications@github.com>) wrote:

And thanks @boonebgorges<https://github.com/boonebgorges> -- I haven't used this theme in a long time, so I appreciate the fixes as I was unaware the new version of WordPress broke things.

**Pull request merged**
